import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar";
import SideNavbar from "@/components/sideNavbar";
import { Poppins } from 'next/font/google';
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
const poppins = Poppins({ subsets: ['latin'],weight: ["100", "300", "400", "700", "900"], variable: '--font-poppins' });

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className="font-poppins antialiased bg-white text-white "
      >
        
        <main className="bg-slate-950 font-poppins">
        <Navbar />
        <div className="flex flex-row w-full">
        <SideNavbar />
        {children}
        </div>
      </main>
      </body>
    </html>
  );
}
